### ISSUE TITLE
Confidence Intervals for Component Interpretation are Off

### ISSUE THREAD

**Issue by tk27182** [ucsf-ferguson-lab/syndRomics#16] opened 2022-02-11 18:09 UTC
Hello, this was a bug that was fixed last year for the communalities plotting, but in the newest v0.1.0, I think there's a similar bug in the code that plots the `permut_pc_test` results to interpret the components.

```
library(syndRomics)
library(ggplot2)
library(dplyr)
library(stringr)
library(mlbench)

# Load the data
data(Glass)

# Delete missing rows
glass.df <- Glass[complete.cases(Glass),]

# Remove columns for classification or that only have 1 unique value
gdf <- Glass[, !(names(Glass) %in% c("Type"))]

# Create PCA
gpca_data <- as.matrix(apply(gdf, 2, as.numeric))

gpca <- prcomp(gpca_data, center = T, scale. = T)

# Extract standardized loadings
gloadings <- stand_loadings(gpca, gpca_data)

# Permute and keep components
set.seed(500)
P <- 500
ndim <- 5

# Component Interpretation
gs_per <- permut_pc_test(gpca, gpca_data, P=P, ndim=ndim, statistic='s.loadings', perm.method = 'permV')

show(plot(gs_per, plot_resample = T))
```
![comp_interp_bug_example](https://user-images.githubusercontent.com/14067153/153645432-c26c9b46-a698-4e70-8b7a-05c14f4ea2fa.png)

**Comment by ATEspin** [comment] 2022-02-11 20:09
Thanks for pointing this out. It does seems odd that the CI are not centered around 0. When reducing ndim to 3, they seem OK. I will look into this.

**Comment by ATEspin** [comment] 2022-06-24 04:45
Sorry this took so long...

I went back to this and the code seems to be OK. I think the problem is that the permutation with permV requires to deal with rotation invariances. In the package we use Procrustes to rotates the permutated solution to the original one as suggested by [Linting et al](https://link.springer.com/article/10.1007/s11336-011-9216-6). The more components you keep in the solution to rotate, the more the rotation capitalize into the random noise, shifting the loadings. The rotation should happen on the "informative" solution, that is to perform permute test with "permV" only on the components that has important contribution (above random chance). 

Here a clear example:

```
pca_data<-mtcars
pca<-prcomp(pca_data, scale. = T, center = T)

vaf_per <- permut_pc_test(pca, pca_data, P=P, ndim=9, 
                         statistic='VAF', perm.method = 'permV')

plot(vaf_per, plot_resample = T)

s_per <- permut_pc_test(pca, pca_data, P=P, ndim=2, 
                         statistic='s.loading', perm.method = 'permV')

plot(s_per, plot_resample = T)

s_per <- permut_pc_test(pca, pca_data, P=P, ndim=3, 
                        statistic='s.loading', perm.method = 'permV')

plot(s_per, plot_resample = T)
```
![image](https://user-images.githubusercontent.com/20674336/175463671-bf7f09dd-facf-4e88-b1e3-85281b250481.png)
![image](https://user-images.githubusercontent.com/20674336/175463682-e45b8460-b451-41bf-a2ae-0c6b6390850e.png)
![image](https://user-images.githubusercontent.com/20674336/175463707-b5d7d928-65ba-4fab-a1b1-029959067f98.png)

You can see that when including PC3 in the permutation the "bad" behaviour of the CI shows up.

Not sure this helps, but I will close this as I don't think is a code problem as much as a limitation on the method. Future work may go on implementing other permutation strategies.

**Closed** 2022-06-24 04:45 UTC

**Comment by tk27182** [comment] 2022-07-12 18:08
That makes sense, thanks for looking into this and explaining the method behind it!
